### PR TITLE
Added support for isEmpty

### PR DESCRIPTION
**Pull request by rankida**
A feature request disguised as a pull request, adding support for [isEmpty](https://www.rethinkdb.com/api/javascript/is_empty/)

### CODE REVIEW

**Comment by hueniverse** [comment]
First, it should be called `empty` to be consistent. Second, it is not very intuitive because it is limited to arrays but empty could mean many things. I think it should be expanded to objects as well (no keys).

**Comment by rankida** [comment]
Thanks.
I did consider `empty` but worried it would clash with `table.empty()`.

I will make those changes now.

**Comment by rankida** [comment]
We have not moved to node 8 yet 😞  so would it be possible to back-port this to v7?

I have done the work https://github.com/hueniverse/penseur/compare/v7.14.0...rankida:isEmpty-v7 but I can't create a PR without a destination branch. If you are willing, can you create a branch from the `v7.14.0` tag and I can create the back-port PR?

**Comment by hueniverse** [comment]
@rankida https://github.com/hueniverse/penseur/tree/7.x

**Comment by rankida** [comment]
Thanks @hueniverse https://github.com/hueniverse/penseur/pull/145

**Pull request merged**
